# 모두를 위한 딥러닝 Lab4_1

In [2]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### Matrix사용 안한 경우

In [13]:
x1_data = [73,93,89,96,73]
x2_data = [80,88,91,98,66]
x3_data = [75,93,90,100,70]
y_data = [152,185,180,196,142]

In [14]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [15]:
w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [16]:
hypothesis = w1*x1 + w2*x2 + w3*x3 + b

In [17]:
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],
                                   feed_dict={x1:x1_data, x2:x2_data, x3:x3_data,y:y_data})
    if step % 100 == 0:
        print(step, "Cost:",cost_val,"\nPrediction:\n",hy_val)

0 Cost: 10088.725 
Prediction:
 [74.055435 70.16011  79.00988  82.4271   52.09861 ]
100 Cost: 51.95345 
Prediction:
 [162.65211 177.18199 184.18156 196.99258 133.83252]
200 Cost: 49.257465 
Prediction:
 [162.37578 177.37097 184.09634 196.93512 134.077  ]
300 Cost: 46.703705 
Prediction:
 [162.10684 177.55495 184.01341 196.87929 134.3149 ]
400 Cost: 44.28441 
Prediction:
 [161.84503 177.73401 183.93265 196.82504 134.54639]
500 Cost: 41.9925 
Prediction:
 [161.59016 177.90831 183.85402 196.77232 134.77164]
600 Cost: 39.82142 
Prediction:
 [161.34207 178.07799 183.77747 196.72108 134.99077]
700 Cost: 37.764763 
Prediction:
 [161.10057 178.2431  183.70293 196.6713  135.20401]
800 Cost: 35.816345 
Prediction:
 [160.86548 178.40387 183.63036 196.62294 135.41148]
900 Cost: 33.97056 
Prediction:
 [160.63661 178.56033 183.55971 196.57594 135.61336]
1000 Cost: 32.22196 
Prediction:
 [160.41383 178.71266 183.4909  196.53027 135.80977]
1100 Cost: 30.565344 
Prediction:
 [160.19693 178.86092 183.42

### Matrix 사용한 경우

In [3]:
x_data = [
    [73,80,75],
    [93,88,93],
    [89,91,90],
    [96,99,100],
    [73,66,70]
]
y_data = [
    [152],[185],[180],[196],[142]
]

In [4]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

In [6]:
W = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [11]:
hypothesis = tf.matmul(X,W) + b

In [17]:
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],
                                   feed_dict={x1:x1_data, x2:x2_data, x3:x3_data,y:y_data})
    if step % 100 == 0:
        print(step, "Cost:",cost_val,"\nPrediction:\n",hy_val)

0 Cost: 10088.725 
Prediction:
 [74.055435 70.16011  79.00988  82.4271   52.09861 ]
100 Cost: 51.95345 
Prediction:
 [162.65211 177.18199 184.18156 196.99258 133.83252]
200 Cost: 49.257465 
Prediction:
 [162.37578 177.37097 184.09634 196.93512 134.077  ]
300 Cost: 46.703705 
Prediction:
 [162.10684 177.55495 184.01341 196.87929 134.3149 ]
400 Cost: 44.28441 
Prediction:
 [161.84503 177.73401 183.93265 196.82504 134.54639]
500 Cost: 41.9925 
Prediction:
 [161.59016 177.90831 183.85402 196.77232 134.77164]
600 Cost: 39.82142 
Prediction:
 [161.34207 178.07799 183.77747 196.72108 134.99077]
700 Cost: 37.764763 
Prediction:
 [161.10057 178.2431  183.70293 196.6713  135.20401]
800 Cost: 35.816345 
Prediction:
 [160.86548 178.40387 183.63036 196.62294 135.41148]
900 Cost: 33.97056 
Prediction:
 [160.63661 178.56033 183.55971 196.57594 135.61336]
1000 Cost: 32.22196 
Prediction:
 [160.41383 178.71266 183.4909  196.53027 135.80977]
1100 Cost: 30.565344 
Prediction:
 [160.19693 178.86092 183.42