# 모두를 위한 딥러닝 Lab6_1
### Softmax classifier

In [1]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

In [3]:
W = tf.Variable(tf.random_normal([4,nb_classes]),name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]),name = 'bias')

In [4]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [5]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(train,feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print(step, sess.run(cost,feed_dict={X:x_data,Y:y_data}))
    
    all = sess.run(hypothesis,feed_dict={X:[[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
    print(all, sess.run(tf.arg_max(all,1)))

0 6.533083
500 0.44312757
1000 0.2661839
1500 0.1989994
2000 0.16333963
Instructions for updating:
Use `argmax` instead
[[2.6367802e-02 9.7362447e-01 7.7822560e-06]
 [7.0642847e-01 2.7360502e-01 1.9966561e-02]
 [1.5182618e-08 3.4885888e-04 9.9965107e-01]] [1 0 2]
