# 모두를 위한 딥러닝 Lab8

In [1]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### 기본 문법
##### rank는 [ ]개수

In [2]:
t = np.array([0,1,2,3,4,5],dtype=np.float32)
print(t)

[0. 1. 2. 3. 4. 5.]


In [3]:
# rank(차원)
t.ndim

1

In [4]:
# shape(배열형태)
t.shape

(6,)

##### 주의! numpy의 array 인수는 단일 list가 되어야함

In [5]:
t = np.array([[0,1,2],[3,4,5],[6,7,8]],dtype=np.float32)
print(t)
print(t.ndim)
print(t.shape)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
2
(3, 3)


##### eval()은 session을 바로 run함

In [6]:
t = tf.constant([1,2,3,4])
print(tf.shape(t).eval(session=sess))

[4]


##### Matrix간의 곱은 반드시 matmul로!

In [7]:
m1 = tf.constant([[1,2],[3,4]])
m2 = tf.constant([[1],[2]])
tf.matmul(m1,m2).eval(session=sess)

array([[ 5],
       [11]])

### Broadcasting 
##### shape이 달라도 연산가능, 큰쪽으로 casting함

In [8]:
# Shape 같은 경우
m1 = tf.constant([1,1])
m2 = tf.constant([2,2])
(m1+m2).eval(session=sess)

array([3, 3])

In [9]:
# Shape 다른 경우
m1 = tf.constant([1,1])
m2 = tf.constant([2])
(m1+m2).eval(session=sess)

array([3, 3])

In [10]:
m1 = tf.constant([[1,1]])
m2 = tf.constant(2)
(m1+m2).eval(session=sess)

array([[3, 3]])

In [11]:
m1 = tf.constant([[1,2]])    # shape = [1,2]
m2 = tf.constant([[3],[4]])    # shape = [2,1]
(m1+m2).eval(session=sess)    # 결과 shape = [2,2]

array([[4, 5],
       [5, 6]])

### Reduce mean : 요소의 평균을 구한다. 
##### type에 주의하자. 

In [12]:
tf.reduce_mean([1,2], axis=0).eval(session=sess)

1

In [13]:
tf.reduce_mean([1.,2.], axis=0).eval(session=sess)

1.5

##### axis를 주어 어떤축을 기준으로 평균을 구할지 알려주자.

In [14]:
x = [[1.,2.],
    [3.,4.]]

In [15]:
# axix=0
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [16]:
# axis=1
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [17]:
# axis=-1은 가장 안쪽의 축
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

### Reduce_sum : 요소의 합을 구한다

In [18]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [19]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3., 7.], dtype=float32)

In [20]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)

### Argmax : 요소의 최댓값의 위치를 구한다.

In [21]:
tf.argmax(x,axis=0).eval(session=sess)

array([1, 1], dtype=int64)

### Reshape : shape를 변형시킨다.
##### 가장 안쪽의 shape는 reshape하지 말기

In [22]:
t = np.array([[[0,1,2],
              [3,4,5]],
             [[6,7,8],
             [9,10,11]]])
t.shape

(2, 2, 3)

In [23]:
tf.reshape(t, shape=[-1,3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##### squeeze : 불필요한 shape를 펴줌

In [24]:
tf.squeeze([[0],[1],[2]]).eval(session=sess)

array([0, 1, 2])

##### expand_dims : dimension 추가해줌

In [25]:
tf.expand_dims([0,1,2],1).eval(session=sess)

array([[0],
       [1],
       [2]])

### One hot : 해당 위치만 1로 다른위치는 0으로 encoding
##### one hot은 rank를 하나 더 expand함

In [26]:
tf.one_hot([[0],[1],[2],[0]], depth=3).eval(session=sess)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

### Casting

In [27]:
tf.cast([1.2, 3.4, 2.9], tf.int32).eval(session=sess)

array([1, 3, 2])

### Stack : 배열을 쌓아준다. 

In [28]:
x = [1,2]
y = [3,4]
z = [5,6]

In [29]:
tf.stack([x,y,z]).eval(session=sess)

array([[1, 2],
       [3, 4],
       [5, 6]])

##### axis를 지정하면 그에 따라 stack

In [30]:
tf.stack([x,y,z],axis=1).eval(session=sess)

array([[1, 3, 5],
       [2, 4, 6]])

### Ones & Zeros like 

In [31]:
x = [[0,1,2],
    [3,2,1]]

In [32]:
tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]])

### Zip

In [34]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
